# Pack Metadata for GitHub Actions and Export Script
client:
  modrinth_id: "KYuEjHC3"
  modrinth_slug: "fantazs-barely-modded"
  pack_name: "Barely Modded"
  minecraft_version: "1.21.11"
  loader: "fabric"
  loader_version: "0.18.4"

server:
  modrinth_id: "MmLJ3gYm"
  modrinth_slug: "fantazs-barely-modded-server"
  pack_name: "Barely Modded Server"
  minecraft_version: "1.21.11"
  loader: "fabric"
  loader_version: "0.18.4"
  custom_datapacks:
    - folder: "DefaultGamerules"
      version: "1.0.1"
    - folder: "more-blocks-fixed"
      version: "1.21.11"
    - folder: "zzz_777-Custom-Rewards"
      version: "1.0.0"
    - folder: "zzz_RecipeRemover"
      version: "1.0.2"