hash-format = "sha256"

[[files]]
file = "config/crash_assistant/config.toml"
hash = "dda257c5c08d7ebc2297837675a7eb42d939116ab0ccc0b123330927bd5bab1d"

[[files]]
file = "config/modmenu.json"
hash = "2462b5644234838d06c6f1e0827869f91d62c0ed978f784d9c437212bb6a1cc0"

[[files]]
file = "config/simpleupdatechecker_modpack.json"
hash = "7fd4b61f4bc4dc91be81da6732f89531650e54fa1392d36b6e49b7f4326e7548"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "439bd90b04467748b2ef785331bc2e0334cc8b0fb78b8d5463bd2779799a651d"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "77777d6d4901caa3b49847bde37722ee3cf81d745cfc2e8ffdd2aca6211418e8"

[[files]]
file = "config/yosbr/config/ambientsounds-client.json"
hash = "d8bbc9b96a97ec2dd252a9d63487fd4e7440a921a7e29af93b08d3e6f5d6965b"

[[files]]
file = "config/yosbr/config/betterf3.json"
hash = "c08de891324c4390779168212daf6eca65c7dedf049600842fb8cd258f817d62"

[[files]]
file = "config/yosbr/config/bobby.conf"
hash = "6ff4da9a5e3a1a7668630318e46fa0bd8917ab1006e1133a0aaa891d9c13a67a"

[[files]]
file = "config/yosbr/config/chatnotify.json"
hash = "b3e8f97c03a57895fb6a37174ece3b9dd9a47c893a4685dab85b7fdeb67afad0"

[[files]]
file = "config/yosbr/config/clientsort.json"
hash = "bd9b4e4749136f44c24701da7d09861e9dc5f510b8ff98511e3ef3f238b9ed25"

[[files]]
file = "config/yosbr/config/commandaliases-client/cit.json"
hash = "987ecd26ffbb56b1c97244f01442942c1d2a80a3cc323502599f85855d0fe906"

[[files]]
file = "config/yosbr/config/held-item-info.json"
hash = "b7384f7652e2bae395e004f059d008d48e09b22d9eb5c80cdee16cd0b1172d69"

[[files]]
file = "config/yosbr/config/mindfuldarkness-client.toml"
hash = "11713cf8c4d2d30dfea8c28f76237205daccf1e93ed30d5951ae4460d784362e"

[[files]]
file = "config/yosbr/config/minihud.json"
hash = "67a6b094e71949ba135acc63d0d23f410a2e815172c15cdab4c58d5799fcadc4"

[[files]]
file = "config/yosbr/config/packed_packs/config.json"
hash = "2e92711ddea4f394304a2e9cfbd4aad2655ab1a26278fd62d0acb86442927c9d"

[[files]]
file = "config/yosbr/config/packed_packs/profiles/resourcepacks/Barely Modded Default.profile.json"
hash = "53a4fdcab7f4468e91f7a258ce59fe660a0d93afa9d49ed5f5b8ddb858421ebf"

[[files]]
file = "config/yosbr/config/peek/peek.properties"
hash = "1bd607de36d14fb66eb29a994912c8b780fc8109dd9ff493fc01174a7374a70b"

[[files]]
file = "config/yosbr/config/polydex.json"
hash = "8d6489ba4349dc2f2bb0db3fe56ace358eb97aa2c3b5336d95109f3fbfb7ae28"

[[files]]
file = "config/yosbr/config/presencefootsteps/userconfig.json5"
hash = "0f2c910e226a167c25f9983aa2232978cb5869090372f44af3378b1d81755cea"

[[files]]
file = "config/yosbr/config/resourcepackchecker/resourcepackchecker.properties"
hash = "059eb121a1847f9c62a5531a91b6801f32e943f09bcbf37dbb1e04c17db18022"

[[files]]
file = "config/yosbr/config/roughlyenoughitems/config.json5"
hash = "27c41ffc6f19a5b75e88a00282918cceb9cba7f982dc9eb46c984797cda19bd9"

[[files]]
file = "config/yosbr/config/rrls.toml"
hash = "3630be880dc7f037238b7e6347201d4f716ffc7e16db0a1498ef2f775cf8f5be"

[[files]]
file = "config/yosbr/config/shouldersurfing-client.toml"
hash = "970f244988b7b1e4307592447d9b4633c57b0d2ab3cc34ea736e7f88afb9a87e"

[[files]]
file = "config/yosbr/config/waveycapes.json"
hash = "0423838d965ecff34525d76f0015a4c0e8dc8965cd59b4b398d2bd2c95de7df0"

[[files]]
file = "config/yosbr/config/zoomify.json"
hash = "b3e581c52520478ed00cee66afd8233e9d4155a884078e61e8356b01552e8941"

[[files]]
file = "config/yosbr/options.txt"
hash = "30d922c10baf3c0ea6017f56449ca0398ec0c9c1003b3674917f649f21c534dc"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "904365e7891802e522e5a35189b7039e18f56a22ab30bd99af59b97ec4b7468e"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "564ba07765d3894f54a5d8886db7cf4b8c8fb8c83f18c8cfb1f042a115b44724"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "7749a788cd34e08e2280dc5e05db1bbf375d7a184d787f682f7df19709a754e3"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "ed50f3b3feba91fa31915aefb40690bc322f37be83490e6b59a443e83a46a542"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ff1763afa21669a76a9ca65735944986ec4ef7a0d440b98ee2154aafa46356c8"
metafile = true

[[files]]
file = "mods/armor-poser.pw.toml"
hash = "a5d332d97f29c1f3b2ca274d9076169e11e71fa6b42f65536004a1d830a37727"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
hash = "1562c21781759f538378d67275bac4497dd15b68b85d13e9c5b613a1ba46cacc"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "2d58b7783694c38d8264f263b9ee1f8b31c1aa9dd98866deb20719b252dc4b47"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
hash = "cad0a9ff3fa91278e077049f8e8db3e51e8ccbaa1990f8291660e8bc088b548a"
metafile = true

[[files]]
file = "mods/better-clouds.pw.toml"
hash = "472ed8323c13b2bdf8efb7617a3ae371418a91768fc2bb5b8314c3351daa7189"
metafile = true

[[files]]
file = "mods/better-f1-reborn.pw.toml"
hash = "90ca1338261e113e8a69b4eae7410faf1567b09f3a71286b6f8ee7b613119a1c"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "6ef53c2c4e506e111b4bd7c1bc8804a5a7dcb2f6e3b79054575e73f6ce61ee94"
metafile = true

[[files]]
file = "mods/better-stats.pw.toml"
hash = "0053fa40707004c6c12761ae8e85e4b7ae892041062d74b700608486dad4ac7c"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "8b1e7e1d6edd89356541f1c817f07d8cb1edc78bb5de22ad17b4adbc40ee1ee3"
metafile = true

[[files]]
file = "mods/bhgc.pw.toml"
hash = "2f04ec554ac81eced90fbd5075a30d2b9e9b72ecf6ebc4ff713f1bf6331f2959"
metafile = true

[[files]]
file = "mods/boat-item-view.pw.toml"
hash = "5ab81359d4654812c2f4dd40f6db5bb51e217a228827d5cc351a40611f05d7de"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "5e097f95b8818e0999b4e867351745441f90c9bcf2a9c68cd19d5d708da4a4a1"
metafile = true

[[files]]
file = "mods/bookshelf-inspector.pw.toml"
hash = "f8bed127a8d0ce700e315151f7f384f183ee197db319689d15414a289915521a"
metafile = true

[[files]]
file = "mods/bundles-beyond.pw.toml"
hash = "15405277b8318d28990a64d0a75fa0082597a313c9f9aa20f0f32b8285a85caf"
metafile = true

[[files]]
file = "mods/centered-crosshair.pw.toml"
hash = "5b200061ba0222cf63271193f1f9f89085cb948fc3825852994f703864bcb1e7"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "092508af534efeb380b9551663980ab1f701d88583a63227d02cb02843335f7a"
metafile = true

[[files]]
file = "mods/chatnotify.pw.toml"
hash = "4c7e38b9ab7afa2ba9a68f33a66fdae792f77f7f57fade0405e1e0c875f3bfb5"
metafile = true

[[files]]
file = "mods/cit-list.pw.toml"
hash = "e23f1ae1ccf1a200255265211d8011e54a68ea116e9fa7748c5bb90da716f474"
metafile = true

[[files]]
file = "mods/clickthrough+.pw.toml"
hash = "4bc421c9867393e643ec08d49e005071c70ec911d77adf39e89ba84439167437"
metafile = true

[[files]]
file = "mods/clientsort.pw.toml"
hash = "45cce9573e88c0e64e9b5f3985ad379bf65de5843b5468d924888b10c3ee9875"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a06ef129798265e0d7249426fb0ed5c506725b0460dc3dfdb975b8978480895e"
metafile = true

[[files]]
file = "mods/commandaliases.pw.toml"
hash = "c6baf0c2dbacf06f361a63e4f5574f8cf0fbb8f659dcfcbe82a35d2f6a76bfb3"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "d8e2eb843f684b6abe48010c4ebf3e1300bd0fe9a4132e2744757d850171f4b7"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "9e4b7af4e25273baee0d9f2bc9f337d3b71ee52bbdd3d470cdcbb6d7876b1a1e"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "e661900027e02f1d44f54559e8d67a0b3b507b831be4eb05ab73a0133b22791e"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "982801b4473e11e6f8c5899f18a260515239dfce397c650c6920fc6ae03f6abb"
metafile = true

[[files]]
file = "mods/cut-through.pw.toml"
hash = "06ecf8909f6baf4ab229bad6e6490b79fa26be7263abc24ca3d3d50102f239eb"
metafile = true

[[files]]
file = "mods/dark-window-bar.pw.toml"
hash = "6b6ae67d7d7f532b9053453ef899e43b271f2f444e818b2b86c19947d148ae80"
metafile = true

[[files]]
file = "mods/durability-tooltip.pw.toml"
hash = "584c4c1c6f904156678e5eda999e959ca37df894dbb720b407993e01acd3eb58"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "af8dc072b8d618de96260fccfa5fab7f79c5ca9679bc3a57473f6df4ce218fff"
metafile = true

[[files]]
file = "mods/elytra-physics.pw.toml"
hash = "3375ef7b3bcce41933167417eecefd42e3330d4fec07b70864ac5b479de8aae7"
metafile = true

[[files]]
file = "mods/emotecraft.pw.toml"
hash = "4d934bc4b56f39d810fe5ebbdafc866c6b5d9c57360af6d0525154ab7dcb7114"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "7a2991786a3523846ee1dcaa4c34c9f1d7a544ea4dbf252df8482b19549009b4"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "c23a1be7641341478b09c5c4f835b5e024a246f9e8521e92905bcab0d0e8cce0"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "6085d2f0a5deabc026667492ac344d9b9007c80ccadb3f916fe9b0ec3037f022"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "39b4f43a271700276ff1ae632cf05f90b85f79670d955b50ced036e363a0efe9"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/fast-trading.pw.toml"
hash = "82f171b2e312712aa6cc65e711c0ef8b229a542aa4b93550b4fdf8b338658e36"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "76a12a836d4c7f0f943a1e391dd2d7b5c4673caa497fff16593d49449376b117"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "b22f1d052eee2810fda73d850dd6f425a1214965e03a5a9dada421abfe74603b"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "11c608b6ef3ca111e9bccd9c4aeb8c47cf0b1f5db48054abc89d6a5f1a978aac"
metafile = true

[[files]]
file = "mods/held-item-info.pw.toml"
hash = "15bce919514325447e487d260ec4458165fb4537ccadb9a0e740df4bcf3cb0ef"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "402069ebe33a1f19e6e5c0c0235267b832ba44617f15ddbdc677faf2a2607e38"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "b7d33095f206cb34dc8cd3d5410a00597439a2fc793f4c158c7a2ecfc7e85e82"
metafile = true

[[files]]
file = "mods/itemswapper.pw.toml"
hash = "a9b5bdeaa6995aabf00d9adf49724fdf18c14527044f708620e07ca58eb027b4"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "fa37926328b6b605cce3ca966e2b50af973a2d1043188da4599f105c2a430606"
metafile = true

[[files]]
file = "mods/jump-over-fences.pw.toml"
hash = "a4edf8b754393b34a8d9a3ec8b16b27c578a7c624c6208d5a6b0eb72781b3132"
metafile = true

[[files]]
file = "mods/kleeslabs.pw.toml"
hash = "80c3b9e5a434a2a6f1b110353dd85c9314fe051240cf4b0876e48366dcd9dbea"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "71255e25b05b6529d6a2873e4db079b7b6541f58a78d872bc19478afcb0ffd1c"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
hash = "9711d569e7594f7ed586d53523ccc262e56fddac13484dd5a5f245e7ae239eb7"
metafile = true

[[files]]
file = "mods/lighty.pw.toml"
hash = "ee1e1c01d6ee07eed1502d0bf20c89c38bddfd777a2a58e2e7d09f623f36c076"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "61e1149d5642bb6bd3d2c718054107fa7a6f1b1044f5573d5ecbab3b94f9e281"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "0e87ab10adb3db84b1d6d2ce8bdd7158878b56c965055056b10ad6cde2634568"
metafile = true

[[files]]
file = "mods/locator-heads.pw.toml"
hash = "3dae24b3d4a5d4a99b5cf5629d5df236e128fddaef9c6202a19f0136769a1bb2"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "498b1e53ad324ef235f61366ead140bde04c3108a51973a17e7de8243c5de208"
metafile = true

[[files]]
file = "mods/mapfrontiers.pw.toml"
hash = "d80a9b26a4ad28640292e43eb15456c5125c9c7e5535c10055c5dffe6c79287a"
metafile = true

[[files]]
file = "mods/mindful-darkness.pw.toml"
hash = "0683c2ebca81c93080e44eccf7c72c5e85a6021fd9cfc861e332eda97801bbbe"
metafile = true

[[files]]
file = "mods/minecraftcapes.pw.toml"
hash = "527b42453fc74625f081d9e7b321c770184cda5c31a4a252539514f81bae6f96"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "6d26fbac2dca7845d5de9e5fbbe3dbcb7541ccb952e4f5f14a92e618d5448965"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "51ff93e279e03cb3cd77a5be0df777cdcd975d35b5149180d9dc724e47168c76"
metafile = true

[[files]]
file = "mods/modmenuc.pw.toml"
hash = "371098025e643d20b3e108c7cf0783afc8aaffba3efb612a741b1825ae0e89ac"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "096bce1d87ff7f759d07ae6501043c5d2db1bcdffb5ea566425843f12ff8e348"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "0544fefc6f04f2b408b2c6b4dd3e4bf7d0a4048f1fad6ddf63357549d7446165"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "44f00c1a0e3d4f8717e805c30c862a597e7856472e72637800fd1a38d73fbd08"
metafile = true

[[files]]
file = "mods/nether-coords.pw.toml"
hash = "6f9524f1214e6fe2017e2c2b6e01d3ddd6384ae7ecb2c5eda24bfa3682b51ff7"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "cd25851cbdaad2dd1957a8086ce54aa4bd3c45be75e1ba49168a54fafbd87898"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "4c4f8569adba682de05800e73690fec8ce64d9d86341862ac6d9315d9dec01eb"
metafile = true

[[files]]
file = "mods/notes.pw.toml"
hash = "4bc5c19eb4c70900c1f9eb5b69745b2fd128cda036e02dd4658d03fee98c71bb"
metafile = true

[[files]]
file = "mods/online-emotes.pw.toml"
hash = "44d30430759b6feb77708591fa0b834ca810b33f4066f73a4eeea2ef08420bae"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "08b89b53c392b5fa29198418df8598404d93c58eae40d432caed797c828adbd5"
metafile = true

[[files]]
file = "mods/otterlib.pw.toml"
hash = "a7aaa19d5a9df2b847686f17f8bdd80ded4097a3880fb89a30175a14ae45c5e2"
metafile = true

[[files]]
file = "mods/packed-packs.pw.toml"
hash = "551cbb16245a12123b6c4ece789012b31a133d50ad3024ec4b9db7d13094d0e5"
metafile = true

[[files]]
file = "mods/particle-effects.pw.toml"
hash = "26dfaa9cd6ac317ed6a53ce7775e7ce20931bc0045b6633c9989f3b710635632"
metafile = true

[[files]]
file = "mods/peek.pw.toml"
hash = "a7ed3b70eee552acb382d218b9ab840d6d8d81fac7491db9d146692c4d870389"
metafile = true

[[files]]
file = "mods/ping-view.pw.toml"
hash = "a25ff2b7f1fe489dcecbbcb67907f15f3e1b18892916615050fb1f741c57440c"
metafile = true

[[files]]
file = "mods/player-animation-library.pw.toml"
hash = "255328a49b5dbf428a2b2abdfbf085e9724e3da9eab498abfbc8372ba5a65cec"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "b39ee5a28d5548d591e8f396d2407893affcc71470d7c058d3287039a960e55d"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "13369d7a10a47895f33629f000945d6bdf43f7b19a9ff1ca2ecfbc209c1ac431"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "548a21f091f48b62c91d69a3857648abc6cc70ea18ebeb2d0b649a6576773a27"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "383d8df46529ce54b4b0574be2fd9eba4f45d8c85aa668604e152fca3e439f5a"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "9f2a46f32204c294717a66c3ce4309a8e0fb07822b67ab52ba4c643842652837"
metafile = true

[[files]]
file = "mods/render-distance-toggle.pw.toml"
hash = "3798b9a10190f821ef843e7bcdb1e7c8c7a365cf06d36e71352b34217859a5c2"
metafile = true

[[files]]
file = "mods/resourcify.pw.toml"
hash = "737cad57d571acc5fc7c8458b61f13e7fc234ba97adc2b6e8700054f4a6b87f2"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
hash = "4a0890e5d860b2c51106274bd9573c6968c0add25712ed14572226337e2c9145"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "db278da4715600e9b96dfd79437f9cd70c5dfb7502be462dff790d570a9fb003"
metafile = true

[[files]]
file = "mods/scribble.pw.toml"
hash = "2f975d6ed6a69da973c7d408acc1989b4fc0e59f7cab0ccafdcfea5a7f7f0630"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "77f6ba8f063840c0d8a58bba2cedc2743d136c1d51cdd28d3506d19e167e08d5"
metafile = true

[[files]]
file = "mods/server-resource-pack-checker.pw.toml"
hash = "340c95b7cd3675d4ea78276c8c200b39d53f1fd16ffafb25c3fad2d57c16acba"
metafile = true

[[files]]
file = "mods/shadeandsaturation.pw.toml"
hash = "d4282cd584ecc42ef6d327e9f5410fed4e2d7dbe393b3644fa0e358057a1153d"
metafile = true

[[files]]
file = "mods/shoulder-surfing-reloaded.pw.toml"
hash = "4f6c09d086f1cd3509883483d241c7db802570660d46e2cd653eb4815e090b78"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "11db2f1acc702cfc92d43efd8800b4b9db54e3c059ec1d35754618adacffc334"
metafile = true

[[files]]
file = "mods/simple-update-checker.pw.toml"
hash = "d58bc721a42323b47c4e860ed12a8bfd66345a6f59c3ed935889fe2255676326"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "9ff1a261860fcb16a7c7f124d738abcdfc1297363412d237540685003ff04d6b"
metafile = true

[[files]]
file = "mods/sit!.pw.toml"
hash = "fabef06432bcdff326ed20419e5d75ae516d653736a8203b7177b67ef0df6e39"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "986e43ff06d2a79effec6e219aca063d7b53a98096c5f63983f23cf54c11c7e5"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "248d96043d3cd40e0d73c02e649d5d55967ebc2ba10e60b58ba75bfba3476425"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "dd8c7eed10a3639d76595603142e1d18f6d26262747138c9442d70311006be5e"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "b01870e848aee7e1a2e19c6530bdd4c479b21a2f6f67134da75210844252d48f"
metafile = true

[[files]]
file = "mods/status-effect-bars.pw.toml"
hash = "3ed900bdfc8331520c122957c64c930a50bd814a722b6367155af675d4bf0e40"
metafile = true

[[files]]
file = "mods/status.pw.toml"
hash = "7d71819071c879a05f15d596b53e91e89925932135637f3aa0507c12cd30f52b"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "0db01c3a00fa869d75551efdd90a227b942f6ab8339426b956297072226341d6"
metafile = true

[[files]]
file = "mods/syncmatica.pw.toml"
hash = "39a3a1247761a61f8e108b31284d748f1a1324d4c7ba87b2e768351b0f8a0e74"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "cf2a50560f03613b7356103544a1f11d38da73fc445b5ec0b5a29c10543c3cfd"
metafile = true

[[files]]
file = "mods/tightfire.pw.toml"
hash = "231d70bed9db87db54bed289c9e6dbcf7bab7a702e6b0f1e82a26d783d3893cb"
metafile = true

[[files]]
file = "mods/vkm.pw.toml"
hash = "e7aef75a8bc5e0f8e7efe932fe19e80c18464cb6ce3c3990501fec47c6981bc2"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "3f5679e5212d0cb5e6700b4d13001d435e60fb9151121e01f83d9f10d296eba5"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "1113d43c39a9866252a83ee50d16aa3ce6fcf749acd84d58b05ca09eba4d187b"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "mods/zannaghs-armor-hider.pw.toml"
hash = "aba7d2324ae6ae86fa1da42d6d1f3e88bed5a7a271ac4fa926301791806e8ecf"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "d74d244b3524bea2326becd2ceaa27b8e231156aba33448533cd29b12ed48318"
metafile = true
