name = "<PACKNAME>"
author = "Fantaz"
version = "<MODPACKVERSION>"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d74d044efd228b7e6b14de62266ac9cb4abfc73f04ebf3545bd0fd35d73b36b7"

[versions]
fabric = "<FABRICVERSION>"
minecraft = "<MINECRAFTVERSION>"

[options]
acceptable-game-versions = ["1.21.11"]
datapack-folder = "datapacks"
