name = "<PACKNAME>"
author = "Fantaz"
version = "<MODPACKVERSION>"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "410293f0c57c3e1c2f281163209015bef253a0d46d7a8c6ffdaa52678848f028"

[versions]
fabric = "<FABRICVERSION>"
minecraft = "<MINECRAFTVERSION>"

[options]
acceptable-game-versions = ["1.21.10"]
datapack-folder = "datapacks"
