name = "<PACKNAME>"
author = "Fantaz"
version = "<MODPACKVERSION>"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88f69a5060a91131008d049b7afb1a8a5c27fb4c0ffb8133863716d9fa3a364b"

[versions]
fabric = "<FABRICVERSION>"
minecraft = "<MINECRAFTVERSION>"

[options]
acceptable-game-versions = ["1.21.11"]
datapack-folder = "datapacks"
