name = "<PACKNAME>"
author = "Fantaz"
version = "<MODPACKVERSION>"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df900936b9854a350d965a21e51d4ea4ad4a1957bb558dbc90991cbe5cb29b37"

[versions]
fabric = "<FABRICVERSION>"
minecraft = "<MINECRAFTVERSION>"

[options]
acceptable-game-versions = ["1.21.10"]
datapack-folder = "datapacks"
