name = "<PACKNAME>"
author = "Fantaz"
version = "<MODPACKVERSION>"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6c5cfe4a0975ff635343bebb963ea804e0a72b0057d7f4709303a6f02bd5f89"

[versions]
fabric = "<FABRICVERSION>"
minecraft = "<MINECRAFTVERSION>"

[options]
acceptable-game-versions = ["1.21.11"]
datapack-folder = "datapacks"
